// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {ScoreOracle} from "../src/ScoreOracle.sol";

/// @title Cross-language Merkle conformance
/// @notice The keeper builds score trees in TypeScript
///         (`packages/keeper/src/merkle.ts`); `ScoreOracle` verifies them in
///         Solidity. Nothing in normal operation checks that those two agree —
///         if they drift, the keeper posts a root the contract cannot verify
///         against, every `rebalance` reverts with `BadProof`, and the vault
///         silently stops rebalancing. That is a failure mode which looks like
///         "the market had no opportunities" rather than like a bug.
///
///         So both sides are pinned. `packages/keeper/src/merkle.test.ts`
///         asserts the TypeScript leaves match values computed with `cast`
///         from the Solidity ABI encoding; this test asserts the contract
///         accepts a root and proofs generated by the TypeScript, for an
///         odd-sized (3-leaf) tree where naive implementations diverge.
///
///         Regenerate with:
///           npx tsx packages/keeper/src/merkle.ts   (see the gen snippet in
///           the Day-2 notes) — then update the constants below.
contract MerkleConformanceTest is Test {
    ScoreOracle internal oracle;

    address internal owner = address(0xA11CE);
    address internal reporter = address(0xB0B);

    uint64 constant ASOF = 1_770_000_000;

    /// @dev Produced by `buildScoreTree` in TypeScript, not by this file.
    bytes32 constant TS_ROOT = 0x8c562054877b24f0953cb255eea9bc657f643423e43da181a6744887c4438eb0;

    function setUp() public {
        vm.warp(ASOF + 60);
        oracle = new ScoreOracle(owner, reporter);
        vm.prank(reporter);
        oracle.postScores(TS_ROOT, ASOF, "ipfs://ts-generated");
    }

    function test_contractAcceptsTypescriptRootForVenue1() public view {
        bytes32[] memory proof = new bytes32[](2);
        proof[0] = 0xd883c16f9cb08a239ac51be3ae46a316cde5537d3cf7a8b14023130d74f21cb2;
        proof[1] = 0xd057100aaa1ca71f2aaf0077f98231357d1ee47707228ac0da1465815ee9d3da;
        assertTrue(oracle.verifyScore(1, 5_000, 900, proof), "venue 1 proof rejected");
    }

    function test_contractAcceptsTypescriptRootForVenue2() public view {
        bytes32[] memory proof = new bytes32[](2);
        proof[0] = 0x0aaa574e41773eb20eb3edfcc6d629be1639fd605dcd4525abbbf764e4517a39;
        proof[1] = 0xd057100aaa1ca71f2aaf0077f98231357d1ee47707228ac0da1465815ee9d3da;
        assertTrue(oracle.verifyScore(2, 6_000, 1_200, proof), "venue 2 proof rejected");
    }

    /// @dev Venue 3 is the promoted odd node: its proof has one element, not
    ///      two. An implementation that duplicated the odd leaf instead of
    ///      promoting it would produce a different root and fail here.
    function test_contractAcceptsTypescriptRootForOddLeaf() public view {
        bytes32[] memory proof = new bytes32[](1);
        proof[0] = 0x5578a26053479f80f018a49a94106eb149484f7830d7ad5dc3406e9a455658ba;
        assertTrue(oracle.verifyScore(3, 7_000, 1_500, proof), "odd-node proof rejected");
    }

    function test_contractRejectsATamperedScore() public view {
        bytes32[] memory proof = new bytes32[](2);
        proof[0] = 0xd883c16f9cb08a239ac51be3ae46a316cde5537d3cf7a8b14023130d74f21cb2;
        proof[1] = 0xd057100aaa1ca71f2aaf0077f98231357d1ee47707228ac0da1465815ee9d3da;
        // Same proof, inflated APY. This is what a compromised keeper would try.
        assertFalse(oracle.verifyScore(1, 5_000, 99_999, proof), "tampered APY accepted");
        assertFalse(oracle.verifyScore(1, 99_999, 900, proof), "tampered score accepted");
        assertFalse(oracle.verifyScore(9, 5_000, 900, proof), "wrong venue accepted");
    }

    /// @dev The leaf encoding itself, checked against `cast`-computed values.
    function test_leafHashMatchesIndependentlyComputedValue() public view {
        assertEq(
            oracle.leafHash(1, 5_000, 900, ASOF),
            0x0aaa574e41773eb20eb3edfcc6d629be1639fd605dcd4525abbbf764e4517a39,
            "leaf encoding drifted"
        );
    }
}
